const Numbers = {
    0: {
        "stick-1": { display: "block" },
        "stick-2": { display: "block" },
        "stick-3": { display: "block" },
        "stick-4": { display: "none" },
        "stick-5": { display: "block" },
        "stick-6": { display: "block" },
        "stick-7": { display: "block" },
      },
    1: {
      "stick-1": { display: "none" },
      "stick-2": { display: "none" },
      "stick-3": { display: "block" },
      "stick-4": { display: "none" },
      "stick-5": { display: "none" },
      "stick-6": { display: "block" },
      "stick-7": { display: "none" },
    },
    2: {
      "stick-1": { display: "none" },
      "stick-2": { display: "none" },
      "stick-3": { display: "block" },
      "stick-4": { display: "none" },
      "stick-5": { display: "none" },
      "stick-6": { display: "block" },
      "stick-7": { display: "none" },
    },
    3: {
      "stick-1": { display: "block" },
      "stick-2": { display: "none" },
      "stick-3": { display: "block" },
      "stick-4": { display: "block" },
      "stick-5": { display: "none" },
      "stick-6": { display: "block" },
      "stick-7": { display: "block" },
    },
    4: {
      "stick-1": { display: "none" },
      "stick-2": { display: "block" },
      "stick-3": { display: "block" },
      "stick-4": { display: "block" },
      "stick-5": { display: "none" },
      "stick-6": { display: "block" },
      "stick-7": { display: "none" },
    },
    5: {
      "stick-1": { display: "block" },
      "stick-2": { display: "block" },
      "stick-3": { display: "none" },
      "stick-4": { display: "block" },
      "stick-5": { display: "none" },
      "stick-6": { display: "block" },
      "stick-7": { display: "block" },
    },
    6: {
      "stick-1": { display: "block" },
      "stick-2": { display: "block" },
      "stick-3": { display: "none" },
      "stick-4": { display: "block" },
      "stick-5": { display: "block" },
      "stick-6": { display: "block" },
      "stick-7": { display: "block" },
    },
    7: {
      "stick-1": { display: "block" },
      "stick-2": { display: "none" },
      "stick-3": { display: "block" },
      "stick-4": { display: "none" },
      "stick-5": { display: "none" },
      "stick-6": { display: "block" },
      "stick-7": { display: "none" },
    },
    8: {
      "stick-1": { display: "block" },
      "stick-2": { display: "block" },
      "stick-3": { display: "block" },
      "stick-4": { display: "block" },
      "stick-5": { display: "block" },
      "stick-6": { display: "block" },
      "stick-7": { display: "block" },
    },
    9: {
      "stick-1": { display: "block" },
      "stick-2": { display: "block" },
      "stick-3": { display: "block" },
      "stick-4": { display: "block" },
      "stick-5": { display: "none" },
      "stick-6": { display: "block" },
      "stick-7": { display: "block" },
    },
  };
  
export default Numbers;